### ISSUE TITLE
Daedalus, what the fuck?

### ISSUE THREAD

**Issue by NycuRO** [iTXTech/Daedalus#1]
@PeratX Why you abandonated Genisys, Cenisys and others?

Why? -_-

You start one project and in two second abandonate it -_-

**Comment by PeratX** [comment]
I WANT TO TEMPORARILY AWAY FROM MINECRAFT DEVELOPMENT.
AND STEP INTO JAVA, JVM AND ANDROID.
THIS PROJECT IS A SMALL AND USEFUL TOOLBOX FOR PEOPLES IN MAINLAND CHINA.

OTHER PROJECTS:
* NEMISYS SERIES - BOYBOOK WILL MAINTAIN IT.
* GENISYS - I DID NOT ABANDON IT, BUT IT IS REALLY MESS.
* AND WHAT OTHERS? CENISYS IS NOT CREATED BY ME.

**Comment by NycuRO** [comment]
ok.

**Comment by NycuRO** [comment]
still you shit for me
