### ISSUE TITLE
Share VPN via Hostpot

### ISSUE THREAD

**Issue by eakteam** [iTXTech/Daedalus#100]
Hi, it would be great if there is any way to share connection from daedalus to other devices via Hostspot

**Comment by PeratX** [comment]
What is Hostpot?

**Comment by eakteam** [comment]
When you enable Portable Hotspot (Tethering) to share mobile internet with other devices...
And this app doesn't work with that ... it would be awesome if it can be done

**Comment by Rsplwe** [comment]
@eakteam Sorry, no root can't do this.

**Comment by eakteam** [comment]
@PeratX can you please write an example how to achieve this ?

**Comment by PeratX** [comment]
Sorry, the detailed code is not public right now, however, I can give some steps.

1. listen all address in VPNService
1. Use something like Pcap4J decode every packet
1. Filter DNSPackets(TCP or UDP)
1. Rewrite IPacket and TCP/UDP header to redirect packets
1. When receive a packet from upstream server, rewrite header again

**Comment by PeratX** [comment]
Maybe this feature will be implement in a separate DNS server. See #105
