### ISSUE TITLE
无法储存服务器配置和规则文件

### ISSUE THREAD

**Issue by leijux** [iTXTech/Daedalus#102]
重开软件后，服务器配置和下载的规则丢失，手机权限里没有储存权限，小米9 安卓9.0

**Comment by Rsplwe** [comment]
@leijux Android 9移除了相关权限，导致了外部存储不可写

**Comment by Rsplwe** [comment]
@leijux 复现失败，可能是小米的锅

**Comment by PeratX** [comment]
应用在自己的目录下储存文件是不需要申请相关权限的
如果无法保存，那就是某些厂商魔改系统出现了问题

**Comment by PeratX** [comment]
Android 9 下问题挺多的，下个月我会调查的。

**Comment by PeratX** [comment]
现在调查到非正常结束应用再次打开会重写配置文件
