### ISSUE TITLE
请求添加 Root/Magisk 模式

### ISSUE THREAD

**Issue by Sodium-Aluminate** [iTXTech/Daedalus#103]
一个系统只能有一个 vpn 活着。
所以在技术上，能不能通过修改 hosts 文件来在别的程序开启时依旧达到去广告的作用呢？

**Comment by HaiVince** [comment]
都root了
老哥为啥不直接修改hosts文件

**Comment by Sodium-Aluminate** [comment]
> 都root了
> 老哥为啥不直接修改hosts文件

因为直接改 hosts 不方便，我也没心情不停的维护之。

**Comment by Rsplwe** [comment]
@Sodium-Aluminate No root required Android DNS modifier and Hosts/DNSMasq resolver.

**Comment by Sodium-Aluminate** [comment]
> @Sodium-Aluminate No root required Android DNS modifier and Hosts/DNSMasq resolver.

我记得好像有一个magisk hosts来着？
