### ISSUE TITLE
hello, Vpn does not work when the application is on the back of Android 9. Xiaomi Redmi Vpn never starts

### ISSUE THREAD

**Issue by MehmetSait** [iTXTech/Daedalus#111]
## Checklist
- [x] I am sure the error is coming from Daedalus's code and not elsewhere.
- [ ] I have searched in the issue tracker for similar bug reports, including closed ones.

## Platform
 - Device: [e.g. Google Pixel 3]
 - OS: [e.g. Android 9.0]
 - Daedalus Version: [e.g. 1.14.0]

## Description
A clear and concise description of the problem.

## Steps to Reproduce
[A minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

## Stacktrace
If it is possible, you can copy `Log` from the app.

**Comment by PeratX** [comment]
Please complete the issue template

**Comment by MehmetSait** [comment]
when app is forground i can see log and i can debuggable, when app is background i can't

**Comment by PeratX** [comment]
You said `never starts`, so please turn on debug in settings and copy log after you click activate button on the main fragment.

**Comment by MehmetSait** [comment]
> You said `never starts`, so please turn on debug in settings and copy log after you click activate button on the main fragment.

this case in Xaomi redmi note 7 plus,  i havn't this phone, i tested on my friends phone if i find that phone i will test it again

**Comment by PeratX** [comment]
My test env includes Android 6.0/8.0 and 9.0, it worked perfectly.
So please provide more details.

**Comment by MehmetSait** [comment]
![Screen Shot 2019-08-15 at 12 12 35](https://user-images.githubusercontent.com/7444533/63085393-17dd9100-bf56-11e9-827f-7f6218de9b23.png)
This screenshot is taken from android version 9.0 running in debug mode. 
There is no log in the console and it does not call the handle request.


![Screen Shot 2019-08-15 at 12 11 17](https://user-images.githubusercontent.com/7444533/63085572-83bff980-bf56-11e9-8c7a-71aa8c4a0815.png)
And this is taken from Android version 10.0 and it works normally. and it works perfectly on android 8.0 and 10.0 versions.

Best regard.

**Comment by solarelf** [comment]
@MehmetSait Mine works with Android Pie 9.0 on Samsung Galaxy TabS4 DeX mode

**Comment by PeratX** [comment]
I assume this is system related issue

**Comment by MehmetSait** [comment]
hi,  i can't capture all dns packets like youtube video domain (r2---sn-nv47lney.googlevideo.com) and www.googleadservices.com, pagead.l.doubleclick.net., www.googleapis.com, play.googleapis.com. ...

**Comment by PeratX** [comment]
locally resolved?

**Comment by MehmetSait** [comment]
No, I can't resolve

**Comment by PeratX** [comment]
SDK is now Android 29, Tested on Android Q. cannot reproduce.
