### ISSUE TITLE
App and service gets killed in low memory situations.

### ISSUE THREAD

**Issue by soenkegissel** [iTXTech/Daedalus#112]
## Checklist
- [X ] I am sure the error is coming from Daedalus's code and not elsewhere.

## Platform
 - Device: [e.g Wiko Lenny 4, Samsung S7]
 - OS: [Android 7.0]
 - Daedalus Version: [1.14.1]

## Description
In low memory situations and app gets closed. With the app the service closes.

## Steps to Reproduce
Fill the RAM

## Screenshots
![WikoLenny4a](https://user-images.githubusercontent.com/13346316/64913293-938d5200-d73d-11e9-9ebd-53023c2a9d4a.gif)

**Comment by PeratX** [comment]
Low memory. hmmm

**Comment by soenkegissel** [comment]
I added the startForeground method of Android service to the services onstartcommand method.
After adding the app having an app not responding issue.

**Comment by soenkegissel** [comment]
I got a little more information here.
On my example phone, the Wiko Lenny 4, an app called One Clean is preinstalled which shuts down the app. Whitelisted the app in One Clean's settings worked.

I found [that](https://fabcirablog.weebly.com/blog/creating-a-never-ending-background-service-in-android) idea of a never ending background service and tomorrow I will start adopting it to Daedalus.

**Comment by PeratX** [comment]
That will be great
