### ISSUE TITLE
使用当前网络 DNS 为 VPN 的 DNS，仅应用规则

### ISSUE THREAD

**Issue by EricInBj** [iTXTech/Daedalus#113]
读取当前网络（wifi 或者 3g 4g）的 DNS 地址，也就是说不修改 DNS 设置，只是应用规则，达到类似 dnsmasq 的默认 upstream 仍然从 resolve 文件中读取，只是加入了一些 address=/xxx.com/xx.xx.xx.xx 这样的效果。

有这个需求主要是指定一个 DNS 的话，会影响 CDN， 微信图片都刷不出来。

不知道有没有别的小伙伴有这需求？

**Comment by PeratX** [comment]
那必须得能获取到本机的dns服务器，这个怎么做呢？我是没什么思路

**Comment by PeratX** [comment]
已加入。
Jenkins测试版：http://dev.itxtech.org:10298/job/Daedalus/96/artifact/app/build/outputs/apk/pure/debug/org.itxtech.daedalus_1.14.1_37fa796-pure-debug.apk

**Comment by EricInBj** [comment]
这么快

我之前做过一个非常糙的改造，能用，但也只是能用而已。
有个问题就是我的改动里面只关注了 wifi 4g 切换这种情况，在4G 网络下位置变更后移动网络的配置信息应该是变更了的，但没获取到这个事件。


我看了一下你的实现，似乎没做网络变化的处理呢

**Comment by PeratX** [comment]
那应该需要注册一个broadcaster Receiver

**Comment by EricInBj** [comment]
是的，不过应该是只能响应 wifi 和 4G 切换
4G 的基站切换不行，刚搜了一下，也许这个可以？
https://developer.android.com/reference/android/telephony/PhoneStateListener.html#onCellLocationChanged(android.telephony.CellLocation)

**Comment by PeratX** [comment]
应该无需考虑4G基站切换

**Comment by EricInBj** [comment]
我之前改成过网络切换了自动重连，也就是 VPN 会一直是活动状态。
从公司到家里的话网络就不行了，刷不出来微信图片什么的（一直是 4G）。
所以怀疑是 4G 网络虽然没有经历断线重连，但有可能是变更了 IP 及 DNS 设置？不确定，因为没有深入看原因。。重连一下就能好。

**Comment by PeratX** [comment]
如果v4 v6切换 不支持 必须重启服务
4g已经支持v6了

**Comment by EricInBj** [comment]
我更新最新代码试试

**Comment by EricInBj** [comment]
4G 网络下的 DNS 是个公网 IP 地址，所以我之前的猜测可能是错的，应该是不需要变更上游的。
之前我的修改长时间会需要重启也许是我加了太多日志输出，我把所有 DNS 解析记录都记内存里了。。。。。。
