### ISSUE TITLE
B

### ISSUE THREAD

**Issue by mandor786** [iTXTech/Daedalus#114]
## Checklist
- [x] I am sure the error is coming from Daedalus's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.

## Platform
 - Device: [e.g. Google Pixel 3]
 - OS: [e.g. Android 9.0]
 - Daedalus Version: [e.g. 1.14.0]

## Description
A clear and concise description of the problem.

## Steps to Reproduce
[A minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

## Stacktrace
If it is possible, you can copy `Log` from the app.

**Comment by PeratX** [comment]
Close for missing detail
