### ISSUE TITLE
DNS relay option

### ISSUE THREAD

**Issue by avoidik** [iTXTech/Daedalus#115]
Hi,

The idea is to install Daedalus somewhere on Android device and run it as a DNS relay server for internal clients inside the same LAN network where Android device is, access to the DNS relay port may have additional options like allowed CIDR range.

What do you think?

**Comment by solarelf** [comment]
@avoidik This idea is a next step to #105 I suppose? But #105 is not yet released, am I right?

**Comment by avoidik** [comment]
@solarelf correct, I'll close this as duplicate
