### ISSUE TITLE
compile app error in API 30

### ISSUE THREAD

**Issue by abolpv** [iTXTech/Daedalus#119]
## Checklist
- [x] I am sure the error is coming from Daedalus's code and not elsewhere.
- [x] I have searched in the issue tracker for similar bug reports, including closed ones.

## Platform
 - Device: Google pixel 
 - OS: 10.0+
 - Daedalus Version: last version git

## Description
when you sync deadalus with new android gradleAND COMPILE WITH ANDROID API 30 (10+) you get error in build outpot:

\

## Stacktrace
C:\Users\myuser\Desktop\Daedalus-master\app\src\main\java\org\itxtech\daedalus\fragment\DnsTestFragment.java:285: error: query(DnsMessage,InetAddress,int) in DnsQuery cannot override query(DnsMessage,InetAddress,int) in AbstractDnsDataSource
public DnsMessage query(DnsMessage message, InetAddress address, int port) throws IOException {
^

**Comment by abolpv** [comment]
'query(DnsMessage, InetAddress, int)' in 'org.itxtech.daedalus.fragment.DnsTestFragment.DnsQuery' clashes with 'query(DnsMessage, InetAddress, int)' in 'org.minidns.source.NetworkDataSource'; attempting to use incompatible return type

**Comment by PeratX** [comment]
api needs to be updated i think

**Comment by PeratX** [comment]
https://github.com/iTXTech/Daedalus/tree/api-31
