### ISSUE TITLE
using "#" in DNSMASQ list

### ISSUE THREAD

**Issue by K1GP** [iTXTech/Daedalus#120]
Hi
I add 
    address=/#/0.0.0.0
in DNSMASQ list for testing block all dns requests
Rule was load successfullly but app(e.g chrome) can still reach any site
There was no effct at all
Is there anything I have missed?

**Comment by PeratX** [comment]
# is not supported

**Comment by K1GP** [comment]
Got it,thx anyway.
I just see there is a blocklist mode
can I use that to blocking any other app's connections except the chosen one?
Many thanks.

**Comment by PeratX** [comment]
# is supported
