### ISSUE TITLE
anti-ad的dnsmasq规则,日志显示 [INFO] Loaded 0 rules

### ISSUE THREAD

**Issue by yeezylife** [iTXTech/Daedalus#122]
我在规则中添加了anti-ad的dnsmasq规则
规则类型:DNSMasq
规则文件名:anti-AD.dnsmasq
规则下载地址:https://anti-ad.net/anti-ad-for-dnsmasq.conf

但是我发现没有过滤效果,进日志查看有如下字样:
2021-05-11 13:50:14 [INFO] Loaded 0 rules
2021-05-11 13:50:14 [INFO] Loading DNSMasq configuration from /storage/emulated/0/Android/data/org.itxtech.daedalus/files/rules/anti-AD.dnsmasq

anti-ad的dnsmasq列表语法似乎是这样的:
address=/00-gov.cn/
address=/kwcdn.000dn.com/
address=/kwcscdn.000dn.com/
address=/kwflvcdn.000dn.com/
后面没有0.0.0.0 是由于这个原因导致规则未能识别吗..

**Comment by yeezylife** [comment]
anti-ad的dnsmasq列表语法似乎是这样的:
address=/00-gov.cn/
address=/kwcdn.000dn.com/
address=/kwcscdn.000dn.com/
address=/kwflvcdn.000dn.com/
后面没有0.0.0.0   是由于这个原因导致规则未能识别吗..

**Comment by PeratX** [comment]
不是的，这种格式好像暂不支持

**Comment by PeratX** [comment]
已添加测试支持
