### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ydjoe** [iTXTech/Daedalus#14]
增加一种策略让首选DNS解析失败或无效地址时尝试让备选DNS来解析，另外这个功能如能实现希望能继续开发个桌面版，谢谢

**Comment by PeratX** [comment]
首选解析失败自动使用备选的，这是Android系统的机制。

**Comment by ydjoe** [comment]
就是WINDOWS系统好像在主要DNS不坏的时候就会一直使用它（测试过），我想设置成主DNS为运营商DNS备用DNS为翻墙DNS，当主DNS解析错误时自动让备用DNS来尝试解析，不知这一功能可否实现？

**Comment by ydjoe** [comment]
或者是SSR中的那个chinadns ，普通DNS分开的功能的原理也行

**Comment by PeratX** [comment]
其实你可以这样实现，在【服务器】中手动添加运营商DNS服务器，然后在【规则】中定义需要自定义的解析内容。
