### ISSUE TITLE
请问如何使用本地dnsmasq规则

### ISSUE THREAD

**Issue by Makebignew** [iTXTech/Daedalus#16]
在设置里看到有启用本地规则解析，但没有看到导入本地规则的选项。

**Comment by PeratX** [comment]
为何没有导入本地规则的选项？
* 本应用不请求读取储存设备权限，无法读取文件（怕麻烦┑(￣Д ￣)┍）
* 怕麻烦┑(￣Д ￣)┍
* 怕麻烦┑(￣Д ￣)┍

如何手动导入？
1. 使用某些【文件浏览器】将需要导入的规则文件【复制】/【剪切】到【/sdcard/Android/data/org.itxtech.daedalus/files/rules】文件夹下（如果你有其他的规则的话，你应该能看见那些规则的储存文件）。
2. 启动本应用，在【规则】界面点击右下角悬浮【添加】按钮，填写相关信息，文件名一项即为刚才【复制】进去的文件的文件名。
3. 在【规则】界面点击该规则，看到左边从灰色变成绿色即为启用成功，请重新启用服务。
