### ISSUE TITLE
dnsmasq泛解析问题

### ISSUE THREAD

**Issue by vovoa17** [iTXTech/Daedalus#19]
我在dnsmasq的配置文件中有一条：`address=/gvt1.com/10.0.0.1` 但是我发现解析r2---sn-i3b7kn76.gvt1.com的时候并不会解析到10.0.0.1

**Comment by PeratX** [comment]
那一定是你的错觉（逃
好吧，你可能是看见了直接连接DNS查看的结果而忽略了向本地DNS查询的结果，10.0.0.x查询的结果才是正确的结果。
