### ISSUE TITLE
Add backend socks5 proxy support

### ISSUE THREAD

**Issue by milkice233** [iTXTech/Daedalus#20]
It's known that this tiny tool help get rid of DNS pollution so users can access some regulated websites.However, this app can't deal with 2 special situations.

1. Specific IP are banned by ISP or authorities.
2. Some websites actively refused connection from a certain region or country.

For the 2 situations above, the only solution is to change external IP, or in other words, go through a socks5 proxy in order to bypass these limitations. And here's my idea of solution:

- [x] A bypass list must be built and users can add IP/domains to it
- [x] When resolving domains, check if this domain is in bypass list, if true, resolving the domain through socks5 proxy, and let all the data to this websites go through socks5 proxy.
- [ ] When accessing a specific IP directly instead of resolving from a domain, check if the IP is in bypass list, if true, redirect all the data to socks5 proxy

Theoretically speaking, the enhancements above aren't too hard to implement. And I'm also glad to contribute for the features.

**Comment by PeratX** [comment]
When accessing a specific IP directly instead of resolving from a domain, check if the IP is in bypass list, if true, redirect all the data to socks5 proxy

This requires a universual trunnel. 0.0.0.0
