### ISSUE TITLE
看你代码有hosts使用,如何使用

### ISSUE THREAD

**Issue by hhhaiai** [iTXTech/Daedalus#24]
如何使用hosts?

**Comment by PeratX** [comment]
https://github.com/iTXTech/Daedalus/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C

**Comment by hhhaiai** [comment]
非常感谢您的回复. 您的app的内置规则,看到了你的hosts,如果让其生效呢?
是否是hosts 翻墙效果?

**Comment by hhhaiai** [comment]
知道怎么用了,我的错, sorry

**Comment by PeratX** [comment]
不客气哦
