### ISSUE TITLE
How do I import it into my AndroidStudio?

### ISSUE THREAD

**Issue by Rehtt** [iTXTech/Daedalus#3]
Prompt：CreateProcess error=2，系统找不到指定文件

**Comment by PeratX** [comment]
本项目采用IntelliJ IDEA创建，尝试 import from existing project 然后选择 Gradle 项目。导入之后会提示检测到Android框架，点击确定，然后配置SDK。
或 请提供更加详细的信息。

**Comment by Rehtt** [comment]
好的,谢谢

**Comment by PeratX** [comment]
解决之后请close issue，谢谢。
