### ISSUE TITLE
Cannot Connect Google.com & play store

### ISSUE THREAD

**Issue by zoujialing125** [iTXTech/Daedalus#38]
It's strange, same hosts file on PC is normal, can access google.com and play store, but on my phone cannot. Meanwhile, facebook and Youtube is very fast... So, what's the reason?

**Comment by zoujialing125** [comment]
Just tried change to DNSPod DNS server, can access google.com via browser now, but play still cannot.

**Comment by PeratX** [comment]
Tracking in #37
