### ISSUE TITLE
failed to reactivate itself

### ISSUE THREAD

**Issue by cubakcabak** [iTXTech/Daedalus#40]
Daedalus is not reactivate itself after the network state changed.

case in point:
- after the phone start in tethering, Daedalus is stopped by system (as in android design, vpn can't be used in tethering mode), and when the tethering is stopped Daedalus is not reactivate itself.
- when airplane mode invoked, Daedalus is stopped, but when airplane mode is off Daedalus is not reactivate itself.

all other apps that make use the vpnservice has no problem with those cases. they reactivated themselves just fine.

**Comment by PeratX** [comment]
On my phone (Android 5.0.1), when I turn on air mode, VPN service is still active.

**Comment by cubakcabak** [comment]
my phone is android 6.0.1

i dont have extra device with different android version to test on.

**Comment by PeratX** [comment]
Got it, I will investigate it.

**Comment by cubakcabak** [comment]
alright, some follow up.

after i investigate things, it seems that Daedalus not restarting itself if there's more than one vpn apps installed on the system.

for the record, those vpn app itself is not enabled and doesn't set to activate on boot, i just have it installed and non active.

**Comment by PeratX** [comment]
I am sorry. I cannot reproduce that issue even I am calling somebody else, the VPN Service is still active.

**Comment by PeratX** [comment]
Close for cannot reproduce
