### ISSUE TITLE
Adding English manual to Wiki Page

### ISSUE THREAD

**Issue by roviury** [iTXTech/Daedalus#42]
Actually it is very useful. 
For me, I can use proxy server listed in cnproxy with this app to access resources in cn

Give you the translation of the manual. So more people can use it. And you can get improvement.
[manual-eng.txt](https://github.com/iTXTech/Daedalus/files/1327708/manual-eng.txt)

============

I think there are different purposes to use this tools.
I suggest some DNS and rules that I use.
some built-in rules cause problems for non-cn users.

UltraDNS1: 156.154.70.1:53
UltraDNS2: 156.154.71.1:53
GoogleDNS1:  8.8.8.8:53
GoogleDNS2: 8.8.4.4:53

rules
adaway - block general ads #
https://adaway.org/hosts.txt

go-hosts-block . - block google ads #
https://raw.githubusercontent.com/Lerist/Go-Hosts/master/hosts-ad

============

and also some rules from "unblockcn" but don't want to talk it here.

**Comment by PeratX** [comment]
thanks for the translation, I will format it into Markdown some days later. (Incoming is the Chinese national day, from 10.1 to 10.7

**Comment by PeratX** [comment]
https://github.com/iTXTech/Daedalus/wiki/Manual
Done!
