### ISSUE TITLE
能否做成点开应用，自动开启？
How about enable hosts automatically while open the APP?

### ISSUE THREAD

**Issue by frankiezdh** [iTXTech/Daedalus#46]
能否做成点开应用，自动开启？
How about enable hosts automatically while open the APP?

**Comment by PeratX** [comment]
难道现在的操作很繁琐吗。

**Comment by frankiezdh** [comment]
不繁琐。只是有些手机（比如华为）每次都杀进程，启动都要点一下，很是不方便

**Comment by PeratX** [comment]
不能加入白名单吗。我都是根据AOSP开发的。

**Comment by nkdsink** [comment]
那能不能新增當wifi切換到3G/4G移動網路時自動開啟的選項?
感謝

**Comment by PeratX** [comment]
学业繁忙恐怕无时间更新，谢谢支持。嗯，我会计划一下的 @nkdsink
