### ISSUE TITLE
能否增加dark theme?

### ISSUE THREAD

**Issue by nkdsink** [iTXTech/Daedalus#47]
首先感謝開發者製作如此方便的應用!
請問能不能增加dark theme? 萬分感謝。

**Comment by PeratX** [comment]
这个提议不错哦，已加入Todo List

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/31572626-1818c3f8-b0dd-11e7-8fb3-4a0ad136221f.png)
![image](https://user-images.githubusercontent.com/13656668/31572627-1b2eba48-b0dd-11e7-98f6-fd109b6f2759.png)
![image](https://user-images.githubusercontent.com/13656668/31572629-208f21f8-b0dd-11e7-83f1-136eb424ad31.png)
![image](https://user-images.githubusercontent.com/13656668/31572631-2575b24a-b0dd-11e7-9c12-8fadb8cd79f1.png)

卡片样式不正确，正在调试

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/31572672-d2b02b3e-b0dd-11e7-8314-f0b5f78229e8.png)
这样如何呢

**Comment by PeratX** [comment]
http://dev.itxtech.org:10298/job/Daedalus/14/artifact/app/build/outputs/apk/org.itxtech.daedalus_1.10.2_2220ab9-debug.apk 测试版，需要删除已安装的正式版。

**Comment by nkdsink** [comment]
@PeratX 非常漂亮！感謝作者！
