### ISSUE TITLE
老是被腾讯视频等APP杀掉

### ISSUE THREAD

**Issue by cancelpj** [iTXTech/Daedalus#48]
有没有什么方法免杀，提供个小工具自行随机命名打包？

**Comment by PeratX** [comment]
您如果可以证明是被腾讯视频杀掉而不是系统的话，那我也无能为力了。毕竟老流氓还是老的辣。

**Comment by cancelpj** [comment]
作者您好！我是小米NOTE2手机，MIUI 9.7.9.28开发版。经我实测，包括搜狐视频、优酷、爱奇艺、哔哩哔哩、自带的小米视频等5个大众视频软件，都不会影响Daedalus（当然Daedalus也不能去除优酷和爱奇艺的广告）。
唯有腾讯视频一打开Daedalus就消失了，并且即使把腾讯视频切换到后台，再次启用Daedalus，只要腾讯视频切换到前台不到一秒钟就Daedalus消失。

探究一下，安卓APP在各自的虚拟机里面独立运行，我也没ROOT，没给腾讯视频管理权限，它能杀掉其它APP进程，是不是证明安卓系统的安全性问题？

**Comment by PeratX** [comment]
不太清楚了。
