### ISSUE TITLE
我的编译器报错缺少google-services.json

### ISSUE THREAD

**Issue by Rehtt** [iTXTech/Daedalus#5]
Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\dsres\Downloads\GitHub\Daedalus\app\src\debug\google-services.json
  C:\Users\dsres\Downloads\GitHub\Daedalus\app\google-services.json

**Comment by PeratX** [comment]
#3 中我提到过，如果需要调试请注释掉firebase和gcm相关引入。gradle配置文件中
