### ISSUE TITLE
内置多个DNS服务器已经停止服务了

### ISSUE THREAD

**Issue by GrimNew** [iTXTech/Daedalus#50]
Pure，Cute官方停止服务，Fun也已经用不了了，众所周知的原因，DNS服务器也越来越难生存，希望有很多稳定可用的DNS服务。

**Comment by PeratX** [comment]
请理解，本程序只提供技术， __永远不会__ 提供服务。PureDNS已经移除，CuteDNS应该还能用，FunDNS节点还未更新。

**Comment by PeratX** [comment]
还有，十九大期间，FunDNS暂停服务，低调，低调。

**Comment by FindHao** [comment]
这些dns服务器，没有hosts，啥也干不了。hosts没用了。自然他们就停了。
