### ISSUE TITLE
关于ipv6的问题

### ISSUE THREAD

**Issue by IsoaSFlus** [iTXTech/Daedalus#51]
在我手机的rom上似乎找到了A记录就不会考虑AAAA，只有像ipv6.google.com这种只有v6的域名才会使用v6，据说在国产rom里边这样的现象很常见？所以我想能不能加一个只使用AAAA记录的功能（在同时有A和AAAA的时候）。

**Comment by PeratX** [comment]
当系统只能获取ipv6地址的时候，就会只查询AAAA了。否则都是v4优先的。

**Comment by PeratX** [comment]
就是本程序吧所有A记录强行查询AAAA，返回的包会直接被系统丢弃的。因为查什么记录，就应该返回什么记录。

**Comment by IsoaSFlus** [comment]
@PeratX 但我在电脑上测试的结果是有v6则优先v6的（windows linux都如此），虽然说是查什么返回什么，但能不能模拟ipv6.google.com这种只有AAAA记录的模式呢？

**Comment by PeratX** [comment]
系统问题的话，我也无能为力。

**Comment by PeratX** [comment]
你可以打开调试输出，研究一下日志，看看查询的返回结果，是否是先查询A记录，没有，再查询AAAA记录的

**Comment by IsoaSFlus** [comment]
@PeratX最后排查问题发现是由于之前安装了hosts的缘故……删了后系统正常优先使用v6……

**Comment by PeratX** [comment]
很高兴问题得到了解决！
