### ISSUE TITLE
关于服务器和规则保存问题

### ISSUE THREAD

**Issue by GreenChennai** [iTXTech/Daedalus#54]
软件不正常返回退出时，已经保存的规则和服务器就会消失，可怜我花了半小时弄的服务器，全没了×＿×
希望可以快点修复！！

**Comment by PeratX** [comment]
额，这。。。我看看是否可以每个动作都触发保存

**Comment by GreenChennai** [comment]
如果我在后台（后台指的是手机快捷键:桌面:返回:后台运行）把它停止运行，那么我保存的就没有了，如果我正常按返回键退出，则可以保存，我记得有一次他消失了我重启手机之后，他就回来了，不过这种情况只发生过一次……

**Comment by PeratX** [comment]
只需要正常退出该界面就会触发保存
