### ISSUE TITLE
配置规则时建议添加验证规则文件是否正常

### ISSUE THREAD

**Issue by onloadcc** [iTXTech/Daedalus#55]
在配置时使用的github文件地址，刚开始没有选择`Raw`地址，添加后不能用。看了下载后的文件发现是html文件，才想起来需要`Raw`地址。 更改后hosts解析正常。

建议 `同步规则` 时添加下验证文件是否正确。

这个坑找的啊

**Comment by gongfeibiwang** [comment]
我不知道怎么用呢

**Comment by PeratX** [comment]
您说说校验的思路?

**Comment by onloadcc** [comment]
在添加`配置规则`界面点击确认保存时，把文件下载从网络下载 下来，可从手机导入的。 使用正则判断下是否符合`hosts`文件规则。

读取文件所有行，保存到集合中。
对每行进行匹配，以`#`开头的忽略。
其它判断格式是否正确。

判断条件：
host文件格式大多是这种，可以写个正则看下是不是正确。如`(\d{1,3}\.){3}\d{1,3}[\s]{1,}[\w.-]{1,}`可以匹配到下面这些。如果所有行都正确，这个hosts文件就是有效的，验证不正确就提示用户文件不对，检查下文件内容是否正确。
`
74.125.237.11    www-oz-opensocial.googleusercontent.com
74.125.237.11    www-hangouts-opensocial.googleusercontent.com
74.125.237.11    www-onepick-opensocial.googleusercontent.com
74.125.237.11    books.googleusercontent.com
74.125.237.11    ci0.googleusercontent.com
74.125.237.11    ci1.googleusercontent.com
74.125.237.11    ci2.googleusercontent.com
`

可能需要多做下测试 ，看有些特殊格式是否验证不过去。

**Comment by PeratX** [comment]
已归档至 #23
