### ISSUE TITLE
坚果Pro Android7.1.1 在测试中能通，在浏览器中打不开 google

### ISSUE THREAD

**Issue by yufeng217** [iTXTech/Daedalus#6]
坚果Pro Android7.1.1 在测试中能通，在浏览器中打不开 google。

求~求~求~ 正确配置姿势。

**Comment by yufeng217** [comment]
之前用的是 1.6 版本，刚才卸载 1.6 安上 1.7，在浏览器中仍打不开 google。

设置如下：
1. 在规则中「从内置规则导入」选择 racaljk/hosts - Hosts，点击「同步规则」，下载的 host 文件为 140.63KB。点亮为绿色。
2. 在「主页」中启用，在「测试」中测试 google.com 能通。
3. 在浏览器中访问 https://www.google.com/ncr 打不开。

沮丧~

**Comment by PeratX** [comment]
请尝试不启用那个规则直接访问Google，因为那个hosts里面的61开头的ip已经被我党查封

**Comment by yufeng217** [comment]
1. 把规则都移除了，重新同步的 fengixng/google-hosts 规则并启用。
2. 在「主页」中启用，在「测试」中测试 google.com 能通。
DNS服务器：123.207.137.88
解析地址：219.76.4.4
解析地址：219.76.4.4
解析地址：219.76.4.4

**Comment by PeratX** [comment]
你的地区是？

**Comment by yufeng217** [comment]
黑龙江省大庆市

**Comment by PeratX** [comment]
通过DNS并不是一种100%可靠的FQ方式，如果多次尝试还是无法访问，请搭建Shadowsocks服务器等。

**Comment by yufeng217** [comment]
好的，谢谢 [抱拳]

**Comment by PeratX** [comment]
但还是要谢谢你的反馈！
