### ISSUE TITLE
快速设置图块相关建议

### ISSUE THREAD

**Issue by MarkussLugia** [iTXTech/Daedalus#60]
开发者您好！我在这里关于快速设置图块有两个建议：
1.点击图块后，daedalus界面会自动弹出，如果能做到SSR那样后台打开感觉会好一些。
2.图块无法热刷新，需要重新进入快速设置才能够查看正确的图块状态（启用/禁用）。
系统版本：RR-N-5.8.5 Android7.1.2

**Comment by PeratX** [comment]
确实，有时间就搞（估计得2月了，笑
