### ISSUE TITLE
hosts规则不起作用

### ISSUE THREAD

**Issue by devil5186** [iTXTech/Daedalus#68]
最先是尝试ipv6的hosts没效果，后来试了下，手动写了个ipv4的hosts文件，里面就一行
111.111.111.111 www.google.com
然后开启服务，结果依旧可以正常访问谷歌，这是说明hosts没生效吗？

**Comment by PeratX** [comment]
您有没有正确设置呢？设置里需要打开 高级 和 规则解析的
