### ISSUE TITLE
implement new dns standard (doh/dot)

### ISSUE THREAD

**Issue by cubakcabak** [iTXTech/Daedalus#69]
RFC new dns over https/tls for added security and bypass internet censorship.

**Comment by PeratX** [comment]
I will investigate it

**Comment by cubakcabak** [comment]
DNS Queries over HTTPS: 
- https://tools.ietf.org/html/draft-ietf-doh-dns-over-https-01

DNS over Transport Layer Security (TLS):
- https://tools.ietf.org/html/rfc7858
- https://tools.ietf.org/html/rfc8310

**Comment by PeratX** [comment]
Ok. I see. And there is a good news that my final exam was finished.

**Comment by PeratX** [comment]
I found Google Public DNS does not follow the ietf draft and use its own request format. But CloudFlare does.
