### ISSUE TITLE
请问是否有计划支持ipv6？

### ISSUE THREAD

**Issue by TeraDew** [iTXTech/Daedalus#7]
一旦启动该软件就无法打开纯ipv6网页了，更遑论使用ipv6的hosts。
请问能否进一步支持ipv6？

**Comment by PeratX** [comment]
有。
但是我这边并没有ipv6的测试环境。

**Comment by PeratX** [comment]
https://github.com/iTXTech/Daedalus/commit/0e180537e8aca91143b6e8099467bb142eea6464
请示一下这个版本。

**Comment by TeraDew** [comment]
我编译了昨天的代码，在软件内置的测试中已经可以ping通ipv6的地址了，但是在浏览器中依旧无法打开ipv6网页，浏览器提示找不到网页的DNS地址。

**Comment by PeratX** [comment]
给我一点时间我去搭建一个ipv6 proxy。但是GFW并不能封锁ipv6内容吧。

**Comment by TeraDew** [comment]
如果你的路由器可以刷openwrt，并且宽带可以分配到独立ip的话，可以用[HE](https://tunnelbroker.net/)的隧道。
另外，GFW是有墙的，不过封锁不是很严。HE的隧道可以绕过墙，相当于直接挂代理了。

**Comment by PeratX** [comment]
我手头一台是磊科的NW714，还有一台刷了OpenWRT的Linksys WRT54G2 V1

**Comment by PeratX** [comment]
https://github.com/iTXTech/Daedalus/commit/d29035f09ae1076a3e301b27d9a984733ca66728
这边又修复一个关于IPv6的问题，请试一下。

**Comment by brvphoenix** [comment]
我现在有条件测试一下最新源码加入的ipv6功能，如果可以给我发一份最新代码编译的apk文件的话，邮箱feixuewhz@gmail.com

**Comment by PeratX** [comment]
@brvphoenix 查收。1.10 BETA

**Comment by brvphoenix** [comment]
@PeratX ipv6可以用了，不过有bug，偶发性无响应，之前版本没有这问题，另外建议增加可以直接使用本地规则，虽然我能找到下载的规则目录，不过感觉增加本地规则选择可能更方便一点

**Comment by PeratX** [comment]
确实如此。无响应是指？

**Comment by brvphoenix** [comment]
@PeratX 在设置或修改配置文件重新启用app的时候，app会卡着

**Comment by PeratX** [comment]
直接修改configuration.json？

**Comment by brvphoenix** [comment]
@PeratX 不是啊，添加或者移除hosts，重新点停用再启用的时候，有时候会出现点不了卡着的情况，其实我也很迷，昨天的时候出现的比较多，今天倒没怎么出现

**Comment by PeratX** [comment]
有没有日志信息。
