### ISSUE TITLE
Doesn't work on 4G / Mobile Data

### ISSUE THREAD

**Issue by rahadiancs** [iTXTech/Daedalus#71]
I'm using Redmi Note 5 Pro AI Dual Camera with latest MIUI based on Android 8.1, no root.

When using Daedalus on WiFi connection, it works. But when using 4G / Mobile Data connection, it doesn't work even if it's activated. I enabled TCP option, but still no effect, it's still use network operator DNS.

On another rooted device with dnscrypt2 (from magisk) using the same SIM card and 4G connection, I can use the dnscrypt configured DNS and bypass the network operator DNS.

**Comment by cubakcabak** [comment]
@rahadiancs your isp transparently intercept the dns to their dns server.

wait for (hopefully) next release, it will support dns-over-https and dns-over-tls.

it's the new dns standard encrypted comparable to dnscrypt.

**Comment by PeratX** [comment]
Daedalus 1.12.0 is going to be released very soon.

**Comment by rahadiancs** [comment]
Thanks, looking forward to it.
