### ISSUE TITLE
自定义DNS、hosts消失的bug

### ISSUE THREAD

**Issue by bydx** [iTXTech/Daedalus#78]
Redmi 5 Plus/MIUI 9.6.3/Android 7.1.2
昨天配置好的DNS和hosts今天又消失了，不过找到了稳定复现的方法：只要在「服务器」或「规则」界面下点击任务键把软件划掉，/sdcard/Android/data/org.itxtech.daedalus/files/config.json就会被清空，能否请作者修复一下？

**Comment by PeratX** [comment]
退出界面自动保存啊，咋就成bug了呢

**Comment by bydx** [comment]
@PeratX 
我提前备份了config.json，被清空后复制回去按上述操作还是被清，应该就是个bug，也许是MIUI的问题吧

**Comment by PeratX** [comment]
已经移除了不必要的多次保存 7cd2fc369be046ea9a6692cd7cbd98250dcae095
