### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Roiyaru** [iTXTech/Daedalus#80]
主动添加的dns服务器数据会被sd卡女佣进行应用清理时删除，能不能优化一下。
能不能将这个博客（https://blog.liyuans.com/archives/pure-dns-collection.html）里可用的dns服务器内置在软件里

**Comment by PeratX** [comment]
>主动添加的dns服务器数据会被sd卡女佣进行应用清理时删除，能不能优化一下。
不能。这是某些软件的算法问题，并非本程序的问题
>能不能将这个博客（https://blog.liyuans.com/archives/pure-dns-collection.html）里可用的dns服务器内置在软件里
正在考虑
