### ISSUE TITLE
可以追加這個嗎?

### ISSUE THREAD

**Issue by edentw** [iTXTech/Daedalus#82]
你好:
可以將 Adblock Plus 的功能移置到程序裡面嗎?
作為補強的動作!
site:https://easylist.to
https://easylist.to/easylist/easylist.txt
謝謝!

**Comment by cubakcabak** [comment]
Daedalus is ip to host based dns redirector.

you can only used host based adblock list with it, such as what adaway use.

**Comment by PeratX** [comment]
只能使用hosts哦，ABP的规则需要作为浏览器插件，等页面渲染完成之后才能用的
