### ISSUE TITLE
google 的 doh 服务问题

### ISSUE THREAD

**Issue by steven7851** [iTXTech/Daedalus#83]
伺服器网址设定 8.8.8.8/resolve 无法解析
但设定 1.1.1.1/dns-query 可以
查询方式都是 DNS over HTTPS (Google JSON)
这是 google dns 的问题吗?

**Comment by PeratX** [comment]
谷歌不支持那样用的呢
dns.google.com/resolve 才行

**Comment by steven7851** [comment]
那只好先把 dns.google.com 的 IP 加到 hosts 了，不然没法解析

**Comment by PeratX** [comment]
是这样的。

**Comment by steven7851** [comment]
有考虑做个白名单功能吗，把 Daedalus 加到 VPN 的白名单就不用麻烦了
