### ISSUE TITLE
Rules seems not being used in Android 7

### ISSUE THREAD

**Issue by simongcc** [iTXTech/Daedalus#92]
I am testing on LG G5 which is running Android 7.
I have turned on Use Local Rule and Allow Dynamic Rule Reloading.
After then activating the server.

Tried the LG G5 run as Wifi Hotspot(eg. 192.168.39.1) or USB Tethering(eg. 192.168.40.111)
In the DNSMASQ list, added the following
address=/site.localhost.bar/192.168.39.2 # which is my computer's address, I asked it to resolve to
or
address=/site.localhost.bar/192.168.40.2

But it never successfully in reading the custom file.
According to the built-in file setting,
the Rule Filename is eg. union.dnsmasq,
if choosing from local file, a filename is automatically generated, should I use it?
if choosing from an internet url file, the Rule filename required to be input manually.
I cannot find documentation details about it.

The domain test inside the rule is still showing unknown.
Is there anything I have missed?
Many thanks.

**Comment by simongcc** [comment]
I have resolved the problem by checking the listening of the DNSMasq in the mac.
It didn't not listen to the required port properly and now it is working by specifying the server in Daedalus to the Mac in different situation such as USB Tethering, WIFI Hotspot and activate it.
Thanks a lot.

**Comment by simongcc** [comment]
Sorry, I reopened ticket because
my previous method is making it working in another way but it still not reading the custom dnsmasq rules in the config file.

**Comment by PeratX** [comment]
Turn on debug in settings and try to open that address.
You will see something in `Log`, upload it please.

**Comment by simongcc** [comment]
@PeratX thanks for closing this and sorry for late reply, the problem is resolved.
Just note here about what I have done to resolve.
My original idea is connecting Android to dnsmasq in Macbook to test the localhost website while travelling with Android AP.

To make it working, the dnsmasq.conf has to be configured working with Android AP.
Details of dnsmasq.conf skip here. (So the main point is how to configure this config file instead, I think I might have misconfigured it but I have forgotten already for the last time I used was around a year ago.)
After that, activate the Android AP and test to see if the localhost site is being resolved properly.
Done.

Thanks again for the time.
