### ISSUE TITLE
[建议]分应用流量控制

### ISSUE THREAD

**Issue by BuSheTeam** [iTXTech/Daedalus#95]
为什么不试着去搞个分应用控制呢？
比如某个应用（的流量）走 DNS Server 而某个应用不走...

**Comment by Yi-Frank** [comment]
@PeratX 大大我先试试呗....vpnserver流量分开应该改的是这里嘛?

DaedalusVpnService.java line 234

```java

public void run() {
        try {
            Builder builder = new Builder()
                    .setSession("Daedalus")
                    .setConfigureIntent(PendingIntent.getActivity(this, 0,
                            new Intent(this, MainActivity.class).putExtra(MainActivity.LAUNCH_FRAGMENT, MainActivity.FRAGMENT_SETTINGS),
                            PendingIntent.FLAG_ONE_SHOT));
            String format = null;

```

**Comment by BuSheTeam** [comment]
@Yi-Frank Emmm...

**Comment by PeratX** [comment]
> @PeratX 大大我先试试呗....vpnserver流量分开应该改的是这里嘛?
> 
> DaedalusVpnService.java line 234
> 
> ```java
> public void run() {
>         try {
>             Builder builder = new Builder()
>                     .setSession("Daedalus")
>                     .setConfigureIntent(PendingIntent.getActivity(this, 0,
>                             new Intent(this, MainActivity.class).putExtra(MainActivity.LAUNCH_FRAGMENT, MainActivity.FRAGMENT_SETTINGS),
>                             PendingIntent.FLAG_ONE_SHOT));
>             String format = null;
> ```

建议看官方文档，我是实在没时间做更新
https://developer.android.com/reference/android/net/VpnService

**Comment by q1534919606** [comment]
大哥  依赖库哪里下载  用什么软件运行

**Comment by PeratX** [comment]
推荐Android Studio，安装好Android SDK之后用Gradle构建

**Comment by PeratX** [comment]
@Rsplwe 已经编写完成
